// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
    // 文档侧边栏
    tutorialSidebar: [
        'intro',
        {
            type: 'category',
            label: '👋🏻 快速上手',
            collapsed: false,
            items: [
                'start-hand/create-manually/index',
                'start-hand/taboostart/index'
            ]
        },
        {
            type: 'category',
            label: '📚 基础技术',
            collapsed: false,
            items: [
                'basic-tech/scheduler/index',
                'basic-tech/dynamic-dependency/index',
                'basic-tech/self-awake/index',
                'basic-tech/event-manager/index',
                'basic-tech/config/index',
                'basic-tech/language/index',
                'basic-tech/database/index',
                'basic-tech/chest-menu/index',
                'basic-tech/item-builder/index',
                'basic-tech/packet/index',
                'basic-tech/papi/index',
                'basic-tech/input-catcher/index',
                'basic-tech/command/index',
                'basic-tech/utilities/index',
                'basic-tech/reflex/index',
                'basic-tech/nms-proxy/index',
            ],
        },
        {
            type: 'category',
            label: '✨ 进阶技术',
            items: [
                'advanced-skills/isolated-classloader/index',
                'advanced-skills/script-jexl/index',
                'advanced-skills/script-javascript/index',
                'advanced-skills/script-kether/index',
                'advanced-skills/kotlinx-serialization/index'
            ],
        },
        {
            type: 'category',
            label: '🎠 拓展技术',
            collapsed: false,
            items: [
                {
                    type: 'category',
                    label: 'Arim - 工具箱',
                    items: [
                        'expanding-technology/arim/index',
                        'expanding-technology/arim/condition-evaluator/index',
                        'expanding-technology/arim/fixed-calculator/index',
                        'expanding-technology/arim/variable-calculator/index',
                        'expanding-technology/arim/item-match/index',
                        'expanding-technology/arim/entity-match/index',
                        'expanding-technology/arim/glow/index',
                        'expanding-technology/arim/weight-random/index',
                        'expanding-technology/arim/item-manager/index',
                        'expanding-technology/arim/folder-reader/index',
                        'expanding-technology/arim/menu-helper/index',
                        'expanding-technology/arim/command-helper/index',
                    ],
                },
            ],
        },
    ],

    // 教学侧边栏 - 暂时为空，后续添加教学内容
    teachingSidebar: [
        {
            type: 'autogenerated',
            dirName: 'teaching',
        },
    ],
};

export default sidebars;
